### ISSUE TITLE
Don't access store directly use props/mapActions/mapState/mapGetters instead

### ISSUE THREAD

**Issue by probil** [liubich/weather-vue#4]
It's not common to see such code in Vue (despite it is valid):

https://github.com/liubich/weather-vue/blob/3bcfc8d2bb5a7b6f4c602c92ea2ce5b62bb4af90/src/components/CurrentWeather.vue#L5

This component does't have to access store at all as you already passing data by props

Let's use this instead
```vue
>Останнє оновлення: {{currentWeather.dateTime}}</p> 
```

**Comment by liubich** [comment]
> >Останнє оновлення: {{currentWeather.dateTime}}</p>

I've tried, but it's do't work.
Doesn't it work with objects?

**Comment by probil** [comment]
@liubich 
1) In `App.vue`, extract `currentWeather` from the store using `mapAction`
```js
import { mapState } from 'vuex'

export default {
  computed: {
    ...mapState(['currentWeather']),
  }
}
```
2) Pass current weather as a prop to `CurrentWeather` in `App.vue`
```vue
<CurrentWeather
  :weather="currentWeather"
  v-if="this.$store.state.isWeatherGot"
/>
```
3) Use `weather` prop in `CurrentWeather.vue`
4)  In `App.vue` extract `getCurrentPositionAndWeather` action as a method:
```js
import { mapActions } from 'vuex'

export default {
  methods: {
    ...mapActions(['getCurrentPositionAndWeather']),
  }
}
```
5) Use new method in `App.vue`
```js
export default {
  created() {
    this.getCurrentPositionAndWeather();
  }
}
```
6) Extract `isWeatherGot` and `errorDesc` from store as computed property
```js
import { mapState } from 'vuex'

export default {
  computed: {
    ...mapState(['isWeatherGot', 'errorDesc']),
  }
}
```
7) Use it in template:
```vue
<template>
  <div id="app">
    <CurrentWeather v-if="isWeatherGot"/>
    <h2
      v-else-if="errorDesc"
      class="weather-container__no-pos"
    >{{errorDesc}}</h2>
  </div>
</template>
```

**Comment by liubich** [comment]
@probil, thanks for detailed instructions
