### ISSUE TITLE
Fix icon's pathes, please

### ISSUE THREAD

**Issue by liubich** [liubich/weather-vue#47]

**Comment by probil** [comment]
@liubich It don't think absolute path is a good fix for the issue. Can you show me your netlify configuration ?

**Comment by liubich** [comment]
@probil, how should I do that?

**Comment by probil** [comment]
I guess you've already fixed that issue by using `BASE_URL` everywhere

Am I correct?

**Comment by liubich** [comment]
Yes. I asked about the netlify configuration.

**Comment by probil** [comment]
I don't need it anymore because I figured out that `BASE_URL` is enough so you can close the issue  :)

**Comment by liubich** [comment]
Closed in PR #49
